### ISSUE TITLE
Causes to generate TypeAdapter 

### ISSUE THREAD

**Issue by ming13** [rharter/auto-value-gson#38] opened 2016-05-12 06:24 UTC
First of all, thank you for the #19—it greatly simplified things. Just wanted to ask—is it possible to eliminate the need of static method returning `TypeAdapter`? For example, the processor can go over the class signature and detect if any methods have `@SerializedName` annotation and, if it does, generate `TypeAdapter` automagically. It is not an ideal solution of course because `@SerializedName` is not mandatory at this point. Wanted to ask about this because after #19 implementation it feels a little cumbersome to keep a static method in every model.

**Comment by rharter** [comment] 2016-05-12 14:45
There was some discussion in #17 about how to identify classes for inclusion, and settled on the public static member since it would be required anyway.  The issue is that the generated classes are package private, so there needs to be a public member in the annotated class since not all value classes will necessarily be in the same package, and the TypeAdapterFactory needs to access them.

**Comment by rharter** [comment] 2016-05-18 07:25
I'm closing this issue as the deliberate decision behind the current functionality has been explained.  If you think I've missed something and this should be reconsidered, you can reopen the issue and continue the discussion.

**Closed by rharter** 2016-05-18 07:25 UTC
