### ISSUE TITLE
Support for Optional field

### ISSUE THREAD

**Issue by dthong** [rharter/auto-value-gson#161] opened 2017-12-27 11:03 UTC
Optional fields are default to `Optional.empty()` in AutoValue, but I got null exception in deserialization. For those Optional fields, should the plugin initialize them to `Optional.empty()` instead of null before passing values from jsonReader?

**Comment by kaibolay** [comment] 2018-07-31 21:44
This is a duplicate of issue #123 - PR #148 fixes the issue, but has been pending for a while...

**Comment by hzsweers** [comment] 2019-01-13 11:03
I think we should make a call for now to just not support these. Modeling absence in general Java code is one thing, but modeling it in JSON is very different, and I'd rather opt for no solution rather than a limited one and encourage better support for normalization from AutoValue via #132.

**Closed by hzsweers** 2019-01-13 11:03 UTC
Labels: enhancement

**Comment by surlyengineer** [comment] 2020-05-29 21:56
FWIW I hear the point about modeling absence in JSON but this feature would be pretty handy.
