### ISSUE TITLE
Jdk9 Support

### ISSUE THREAD

**Issue by kartoffelsup** [rharter/auto-value-gson#164] opened 2018-01-07 09:16 UTC
First of all, thanks for this nice project :) 

When trying to use `auto-value-gson` with jdk9 the following errors occur:
using:
```gradle
  compile('com.ryanharter.auto.value:auto-value-gson-annotations:0.7.0')
  apt('com.ryanharter.auto.value:auto-value-gson:0.7.0')
```
error:
```
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.ryanharter.auto.value.gson.AutoValueGsonAdapterFactoryProcessor could not be instantiated
```
which can be resolved with:
```
  compile('com.ryanharter.auto.value:auto-value-gson:0.7.0')
  compile('com.ryanharter.auto.value:auto-value-gson-annotations:0.7.0')
  apt('com.ryanharter.auto.value:auto-value-gson:0.7.0')
```
but leads to more errors:
```
error: the unnamed module reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module auto.value.gson reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module auto.common reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module javapoet reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module guava reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module gson reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module auto.value.gson.annotations reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
error: module auto.value reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
F:\dev\auto-value-gson-jdk9\src\main\java\module-info.java:1: error: module com.example.gson.auto.value reads package com.ryanharter.auto.value.gson from both auto.value.gson.annotations and auto.value.gson
module com.example.gson.auto.value {
^
9 errors

```
repro:
[auto-value-gson-jdk9.zip](https://github.com/rharter/auto-value-gson/files/1609605/auto-value-gson-jdk9.zip)

**Comment by kartoffelsup** [comment] 2018-01-12 07:52
I'm guessing this is due to both modules using the same package. A possible fix could be to move annotations to its own package.

**Comment by corydolphin** [comment] 2018-02-27 19:12
@kartoffelsup did you any luck working around this, or attempting to split it up yourself? Would be great to get this working on the latest JDK(s). Do you know if the issue also impacts JDK 10?

**Comment by kartoffelsup** [comment] 2018-03-02 20:05
Sorry, I've since moved to Kotlin and no longer needed the library as gson works with data classes.

**Comment by andredasilvapinto** [comment] 2018-10-04 01:46
I have just experienced this problem today. Indeed with Java >=9 modules you cannot have two modules with the same packages.

**Comment by ChristianCiach** [comment] 2018-10-08 14:22
The problem is that `AutoValueGsonExtension.java` imports this:

```
import javax.annotation.Generated;
```

This class does not exist in JDK 9 anymore. For JDK 9 this class should be imported instead:

```
import javax.annotation.processing.Generated;
```

Alternatively auto-value-gson should define a dependency to the maven artifact `javax.annotation:javax.annotation-api`.

Until this is resolved, JDK 9 users (and above) can manually put `javax.annotation', name: 'javax.annotation-api` in the factorypath as a workaround.

**Comment by ChristianCiach** [comment] 2018-10-08 14:36
> auto-common has helpers to resolve the right annotation

Awesome advice! I will try to create a PR for this.

**Comment by hzsweers** [comment] 2018-10-08 20:20
Closed by 186

**Closed by hzsweers** 2018-10-08 20:20 UTC

**Comment by nguyenhuynhdeveloper** [comment] 2024-05-27 03:09
> auto-common có người trợ giúp để giải quyết chú thích phù hợp

I'm still getting the error, can you tell me the specific implementation
